29 search react
ljreaux/Lab-Rats pull request #101
Opened 2024-03-01 16:53 UTC by ljreaux

Added a search bar to the recipes component. Added a message if no recipes are found. Filters the main list, that way it is constantly filtering.

2024-03-01 20:52 UTC, jared23m approved these changes

2024-03-03 20:25 UTC, BarryFullStack requested changes
Currently when you load the page it will display no recipes as the search bar is empty. If you enter some text then remove it all the recipes will then show. Need it to ingore the search bar on load until user enters text.

also nitpick: but it'd be nice if it could also search through the tags. Right now it's only going off title.

2024-03-03 21:08 UTC, BarryFullStack approved these changes
works great!

2024-03-04 23:05 UTC, amead99 approved these changes

2024-03-05 00:17 UTC, merged