Fixing review assignment
ljreaux/Lab-Rats pull request #146
Opened 2024-03-08 06:36 UTC by jared23m

Gets back the correct reviews on the single recipe page.
Removed email and name from public.
AvgRating everywhere possible.

I don't know why these things didn't carry over but we are good once this merges.

2024-03-08 14:13 UTC, ljreaux approved these changes

2024-03-09 02:09 UTC, ljreaux approved these changes

2024-03-09 17:22 UTC, BarryFullStack commented on FE/src/components/UserProfile.jsx
I think this is preventing an edgecase of the logged in user being able to access their own UserProfile and we need to redirect to Account. So far, I have not found a way to get this result with our current main, and this code is going to cause a code conflict with all the changes I made on userProfile

2024-03-09 17:24 UTC, BarryFullStack requested changes
Its going to save me a ton of headaches on merging the UserProfile banch changes if we remove only that code from this. we can save it to be integrated bacjk in on that branch before I merge it, but I had to make my own conditons on fetch and this code is now smack in the middle of those changes.
Everything else I'm fine with and approve.

2024-03-09 17:37 UTC, jared23m commented
> Its going to save me a ton of headaches on merging the UserProfile banch changes if we remove only that code from this. we can save it to be integrated bacjk in on that branch before I merge it, but I had to make my own conditons on fetch and this code is now smack in the middle of those changes. Everything else I'm fine with and approve.

Ok it's reverted back. Sorry, I didn't realize you needed to edit that useEffect

2024-03-09 18:21 UTC, amead99 approved these changes

2024-03-09 18:33 UTC, merged