61 frontend placeholder routes in app
ljreaux/Lab-Rats pull request #62
Opened 2024-02-17 20:45 UTC by BarryFullStack

Front end routes, component files, and latest Vite and installed react-router-dom

2024-02-18 03:13 UTC, ljreaux requested changes
Overall looks good,  everything works. Once the { } are added to props, I approve.

2024-02-18 03:13 UTC, ljreaux commented on FE/src/components/Account.jsx
Line 3, where you are adding your token and set token needs to be inside of { } or we will have issues later. This is an issue in a few different files.

2024-02-18 03:13 UTC, ljreaux commented on FE/src/components/EditRecipe.jsx
Not a big deal but Recipe is misspelled "Reciope"

2024-02-18 03:51 UTC, ljreaux approved these changes
I approve.

2024-02-19 01:45 UTC, amead99 commented on FE/src/App.jsx
> +    <>Hello Lab Rats
Might should wrap this in an header or p tag. Not sure if having unwrapped text will negatively affect anything

2024-02-19 22:31 UTC, jared23m approved these changes
looks good i approve

2024-02-20 02:57 UTC, amead99 commented
approved!

2024-02-20 22:15 UTC, merged